const metadata = {
  title: "Imagine - n1shan1",
  description: "A fullstack application for imagining possibilities.",
  author: "Nishant Dev",
  keywords: [
    "fullstack",
    "application",
    "imagine",
    "image",
    "generator",
    "free",
    "image generator",
    "image generator online",
    "image generator text",
    "google image generator",
    "image generator from text",
    "image generator from words",
    "image generator meme",
    "image generator meme online",
    "image generator meme text",
    "image generator meme words",
    "image generator meme from text",
    "image generator meme from words",
    "image generator meme text online",
    "image generator meme words online",
    "image generator meme from text online",
    "image generator meme from words online",
    "image generator meme text free",
    "image generator meme words free",
    "image generator meme from text free",
    "image generator meme from words free",
    "image generator meme text online free",
    "image generator meme words online free",
    "image generator meme from text online free",
    "image generator meme from words online free",
    "image generator meme text free online",
    "image generator meme words free online",
  ],
};

export default metadata;
